server/__init__.py
from flask import Flask , url_for
from flask_pymongo import PyMongo

server = Flask(__name__)
server.config['SECRET_KEY'] = "ACE202334NOVA"
server.config['MONGO_URI'] =  "mongodb+srv://admin:E145AZY1xoXJm9g5@cluster64459.gwh8ffh.mongodb.net/ace_nova?retryWrites=true&w=majority"

# mongodb_client = PyMongo(server)
# db = mongodb_client.db

from .views import views
server.register_blueprint(views, url_prefix="/")

server/views.py
from copyreg import pickle
from flask import Blueprint, render_template, request, flash, url_for, request
# from server import db

views = Blueprint("views", __name__)

@views.route("/", methods = ["POST", "GET"])
def index():
    return render_template("home.html")

@views.route("/signup", methods = ["POST", "GET"])
def signup():
    if request.method == "POST":
        first_name = request.form['first-name']
        last_name = request.form['last-name']
        email = request.form['email']
        department = request.form['department']
        year = request.form['year']
        phone_no = request.form['phone-no']
        preference_1 = request.form['preference1']
        preference_2 = request.form['preference2']
        preference_3 = request.form['preference3']
        # db.ace_members.insert_one({
        #     "first_name": first_name,
        #     "last_name": last_name,
        #     "email": email,
        #     "department": department,
        #     "year": year,
        #     "phone_no": phone_no,
        #     "preference_1": preference_1,
        #     "preference_2": preference_2,
        #     "preference_3": preference_3,
        # })
    print("Get request")
    return render_template("signup.html")

@views.route("/tgc", methods = ["POST", "GET"])
def tgc():
    return render_template("tgc.html")

@views.route("/contributors", methods = ["POST", "GET"])
def contributors():
    return render_template("contributors.html")

@views.route("/community", methods = ["POST", "GET"])
def community():
    return render_template("community.html")

server/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>{% block title %} {% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/blog/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">



    
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{{(url_for('static', filename='base.css'))}}" rel="stylesheet">
  </head>
  <body>
<div class="container">
  <header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-body-emphasis text-decoration-none" href="{{url_for('views.index')}}"><b>ACE-NOVA</b></a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="btn btn-sm btn-outline-secondary" href="{{url_for('views.signup')}}">Registration</a>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-3 border-bottom">
    <nav class="nav nav-underline justify-content-between">
      <a class="nav-item nav-link link-body-emphasis active" href="{{url_for('views.index')}}">Home</a>
      <a class="nav-item nav-link link-body-emphasis" href="{{url_for('views.tgc')}}">TGC2023-24</a>
      <a class="nav-item nav-link link-body-emphasis" href="{{url_for('views.community')}}">Community</a>
      <a class="nav-item nav-link link-body-emphasis" href="{{url_for('views.contributors')}}">Contributors</a>

      <!-- <a class="nav-item nav-link link-body-emphasis" href="#">Business</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Politics</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Opinion</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Science</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Health</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Style</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Travel</a> -->
    </nav>
  </div>
</div>

<div class="container">
  {% block body %} {% endblock %}
</div>



<!-- footer -->
<footer class="py-5 text-center text-body-secondary bg-body-tertiary">
  <img src="{{url_for('static', filename='assests/git.png')}}" width="20" height="20">
  <a href = "https://github.com/varmor/ace-nova" class="bottomnav-text">GitHub Repo</a> | <a href="https://github.com/varmor" class="bottomnav-text">Varun More</a> | <a href="https://github.com/Padmaj-Nikam" class="bottomnav-text">Padmaj Nikam</a>

</footer>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    </body>
</html>

server/templates/community.html
{% extends 'base.html'%}

{% block body%}
<h1>Community   </h1>
{% endblock%}

server/templates/contributors.html
{% extends 'base.html'%}

{% block body%}
<h1>contributors</h1>
{% endblock%}

server/templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock%}

{% block body %}
<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
      <div class="col-lg-6 px-0">
        <h1 class="display-4 fst-italic">Welcome to Ace Nova Toastmasters Club</h1>
        <p class="lead fst-italic my-3">"Speak with Impact, Lead with Confidence – Ace Nova Toastmasters Club"</p>
        <!-- <p class="lead mb-0"><a href="#" class="text-body-emphasis fw-bold">Continue reading...</a></p> -->
      </div>
    </div>
  
  <!-- Blog view -->
    <!-- <div class="row mb-2">
      <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary-emphasis">World</strong>
            <h3 class="mb-0">Featured post</h3>
            <div class="mb-1 text-body-secondary">Nov 12</div>
            <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="icon-link gap-1 icon-link-hover stretched-link">
              Continue reading
              <svg class="bi"><use xlink:href="#chevron-right"/></svg>
            </a>
          </div>
          <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-success-emphasis">Design</strong>
            <h3 class="mb-0">Post title</h3>
            <div class="mb-1 text-body-secondary">Nov 11</div>
            <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="icon-link gap-1 icon-link-hover stretched-link">
              Continue reading
              <svg class="bi"><use xlink:href="#chevron-right"/></svg>
            </a>
          </div>
          <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          </div>
        </div>
      </div>
    </div> -->
  
    <div class="row g-5">
      <div class="col-md-8">
        <!-- <h3 class="pb-4 mb-4 fst-italic border-bottom">
          From the Firehose
        </h3> -->
  
        <article class="blog-post">
          <h2 class="display-5 link-body-emphasis mb-1">About</h2>
          <p class="blog-post-meta">January 1, 2023 </p>
            <p class="text-start">Welcome to Ace Nova Toastmasters Club – Where Excellence Meets Innovation! At Ace Nova, we are a dynamic community of individuals dedicated to enhancing our communication and leadership skills in a supportive and <br>vibrant environment. Whether you're a seasoned speaker or a novice, Ace Nova provides a platform for growth, <br>encouragement, and constructive feedback. Join us on a journey of self-discovery, where every meeting is an opportunity to shine and where the art of communication is celebrated. Unleash your potential, build confidence, brand forge lasting connections at Ace Nova Toastmasters Club – your launchpad for personal and professional success.</p>
          </article>
          <div class="p-3">
            <h4 class="fst-italic">Socials  </h4>
            <ol class="list-unstyled">
              <li><a href="#">Instagram</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">LinkedIN</a></li>
            </ol>
          </div>
        </div>
  
      <div class="col-md-4">
        <div class="position-sticky" style="top: 2rem;">
          <div class="p-4 mb-3 bg-body-tertiary rounded">
            <h4 class="fst-italic">Score</h4>
            <p class="mb-0"><h2>74</h2></p>
          </div>
  
          <div>
            <h4 class="fst-italic">Announcement</h4>
            <ul class="list-unstyled">
              <li>
                <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                  <svg class="bd-placeholder-img" width="100%" height="96" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
                  <div class="col-lg-8">
                    <h6 class="mb-0">Congratulation! TM Pratham </h6>
                    <small class="text-body-secondary">Congratulations on your outstanding achievement as the HSE Winner at Toastmasters! Your dedication to excellence and effective communication truly sets you apart. Well done! 🏆🌟</small>
                  </div>
                </a>
              </li>
              <li>
                <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                  <svg class="bd-placeholder-img" width="100%" height="96" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>
                  <div class="col-lg-8">
                    <h6 class="mb-0">Congratulation! TM Astha</h6>
                    <small class="text-body-secondary">Heartfelt congratulations on being crowned the ESE Winner at Toastmasters! Your exceptional communication skills and leadership shine brightly. Well-deserved success! 🏆👏</small>
                  </div>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  
  </main>

  {% endblock %}

server/templates/signup.html
{% extends 'base.html' %}
{% block title %} Registration {% endblock%}


{% block body %}
<main class="container">
  <p class="h1"> Registration </p>
  <form class="row g-3" action="#" method="POST">
    <div class="col-md-4">
      <label for="first-name" class="form-label">First Name</label>
      <input type="text" class="form-control " name="first-name"  required>
    </div>
    <div class="col-md-4">
      <label for="last-name" class="form-label">Last Name</label>
      <input type="text" class="form-control " name="last-name"  required>
    </div>
    <div class="col-md-4">
      <label for="email" class="form-label">Email</label>
      <input type="text" class="form-control" name="email"  required>
    </div>
    <div class="col-md-4">
      <label for="department" class="form-label">Department</label>
      <select class="form-select" name="department" required>
        <option selected disabled value="">Choose...</option>
        <option>Artificial Intelligence</option>
        <option>Data Science</option>
        <option>BBA</option>
        <option>Mechanical</option>
        <option>Civil</option>
      </select>
    </div>
    <div class="col-md-4">
      <label for="year" class="form-label">Year</label>
      <select class="form-select" name="year" required>
        <option selected disabled value="">Choose...</option>
        <option>First Year</option>
        <option>Second Year</option>
        <option>Third Year</option>
        <option>Fourth Year</option>
      </select>
    </div>
    <div class="col-md-4">
      <label for="phone-no" class="form-label">Phone No</label>
      <input type="text" class="form-control   " name="phone-no" required>
    </div>
    <div class="col-12">
      <p class="h3">Mentor Preference </p>
    </div>
    <div class="col-md-4">
      <label for="preference1" class="form-label">Preference No 1</label>
      <select class="form-select" name="preference1" required>
        <option selected disabled value="">Choose...</option>
        <option>TM Varun More</option>
        <option>TM Padmaj Nikkam</option>
        <option>TM Pratham Waydande</option>
        <option>TM Sanchit Chemate</option>
        <option>TM Astha Singh</option>
        <option>TM Rajeshree Bhagwat</option>
      </select>
    </div>
      <div class="col-md-4">
        <label for="preference2" class="form-label">Preference No 2</label>
        <select class="form-select" name="preference2" required>
          <option selected disabled value="">Choose...</option>
          <option>TM Varun More</option>
          <option>TM Padmaj Nikkam</option>
          <option>TM Pratham Waydande</option>
          <option>TM Sanchit Chemate</option>
          <option>TM Astha Singh</option>
          <option>TM Rajeshree Bhagwat</option>
        </select>
      </div>
        <div class="col-md-4">
          <label for="preference3" class="form-label">Preference No 3</label>
          <select class="form-select" name="preference3" required>
            <option selected disabled value="">Choose...</option>
            <option>TM Varun More</option>
            <option>TM Padmaj Nikkam</option>
            <option>TM Pratham Waydande</option>
            <option>TM Sanchit Chemate</option>
            <option>TM Astha Singh</option>
            <option>TM Rajeshree Bhagwat</option>
          </select>
          </div>
          <div class="col-md-4">
            <label for="passcode" class="form-label">PassCode</label>
            <input type="text" class="form-control" name="passcode"  required>
    <div class="col-12 my-2">
      <button class="btn btn-primary" type="submit">Submit form</button>
    </div>
  </form>

</main>

{% endblock %}

server/templates/tgc.html
{% extends 'base.html'%}
{% block body%}
<main>

    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">TGC 2023-24</h1>
          <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
          <!-- <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
          </p> -->
        </div>
      </div>
    </section>
  
    <div class="album py-5 bg-body-tertiary">
      <div class="container">
  
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
  
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
  
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
          <div class="col">
            <div class="card shadow-sm">
              <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <div class="card-body">
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                  </div>
                  <small class="text-body-secondary">9 mins</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  
  </main>
{% endblock%}